Task1
sergey-berezin/401_zubkov pull request #1
Opened 2021-10-11 03:05 UTC by AldOgen

2021-10-18 16:23 UTC, sergey-berezin commented on Task1/Program.cs
> +            var cancelTask = Task.Run(() => {
Запуск длинных задач нужно выполнять с опцией TaskCreationOption.LongRunning

2021-11-01 04:53 UTC, AldOgen commented on Task1/Program.cs
> +                cts.Cancel();
Отменяет задачу слежения за нажатием кнопки.

2021-11-01 04:53 UTC, AldOgen commented
Refactor

2021-11-09 16:25 UTC, sergey-berezin requested changes

2021-11-09 16:25 UTC, sergey-berezin commented on Task1/Program.cs
>                  test.Cancel();
Получается, что test.Cancel выполняется в цикле пока не будет нажата ESC?

2021-11-09 16:25 UTC, sergey-berezin commented on Task1/Program.cs
> +                cts.Cancel();
В этой версии проверки отмены `сts` в цикле нет.

2021-11-09 19:37 UTC, AldOgen commented on Task1/Program.cs
>                  test.Cancel();
Случайно удалил закрытие цикла. Это бесконечный цикл, который крутится до момента нажатия EPS. Сейчас все работает.

2021-11-09 19:38 UTC, AldOgen commented on Task1/Program.cs
> +                cts.Cancel();
Сейчас отменяется.

2021-11-10 07:21 UTC, sergey-berezin approved these changes

2021-11-10 07:21 UTC, merged